'use server';

/**
 * @fileOverview Reviews a generated prompt based on criteria like clarity, context, format, and structure.
 *
 * @function generateAndReview - Analyzes a prompt based on the selected scenario and user input, providing feedback.
 * @typedef {Object} ReviewResult - The result of the prompt review, including AI output and evaluations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReviewResultSchema = z.object({
  aiOutput: z.string().describe('The output generated by the AI based on the user prompt.'),
  evaluations: z.array(
    z.object({
      criteria: z.string().describe('The evaluation criteria (e.g., clarity, context).'),
      status: z
        .enum(['非常に良い', '良好', '改善点'])
        .describe('The evaluation status: 非常に良い (Excellent), 良好 (Good), or 改善点 (Needs Improvement).'),
      advice: z.string().describe('Specific advice for improving the prompt.'),
    })
  ).describe('An array of evaluations for the prompt.'),
});

export type ReviewResult = z.infer<typeof ReviewResultSchema>;

const GenerateAndReviewInputSchema = z.object({
  scenario: z.string().describe('The task scenario selected by the user.'),
  prompt: z.string().describe('The prompt generated by the user.'),
});

export type GenerateAndReviewInput = z.infer<typeof GenerateAndReviewInputSchema>;

export async function generateAndReview(scenario: string, prompt: string): Promise<ReviewResult> {
  return generateAndReviewFlow({
    scenario,
    prompt,
  });
}

const promptReviewPrompt = ai.definePrompt({
  name: 'promptReviewPrompt',
  input: {schema: GenerateAndReviewInputSchema},
  output: {schema: ReviewResultSchema},
  prompt: `You are an AI prompt reviewer. You will analyze a user-provided prompt based on the scenario they selected.  Provide feedback on clarity, context, format, and structure.

Here is the scenario: {{{scenario}}}

Here is the prompt: {{{prompt}}}

Output a JSON object with the following schema:
${ReviewResultSchema.description}

Ensure that the "status" field is one of the following strings: "非常に良い", "良好", or "改善点".  These correspond to "Excellent", "Good", and "Needs Improvement", respectively.  Provide specific "advice" for improvements.
`,
});

const generateAndReviewFlow = ai.defineFlow(
  {
    name: 'generateAndReviewFlow',
    inputSchema: GenerateAndReviewInputSchema,
    outputSchema: ReviewResultSchema,
  },
  async input => {
    const {output} = await promptReviewPrompt(input);
    return output!;
  }
);
